
spring.application.name=recp


spring.datasource.url=jdbc:sqlite:patterndb.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

server.address=0.0.0.0
server.port=8090

# TEMPORARY pattern.diagramsimages.localrepository.path=C:\\Travaux_De_Developpement_Locaux\\RECP_SJNvsJN\\RECP_Projet_Dev_juillet_2025\\MockRECP
pattern.diagramsimages.localrepository.path=/app/PatternsDiagramImages